Update Build_OP_Arcadyan_AW1000.yml

diff --git a/.github/workflows/Build_OP_Arcadyan_AW1000.yml b/.github/workflows/Build_OP_Arcadyan_AW1000.yml
--- a/.github/workflows/Build_OP_Arcadyan_AW1000.yml
+++ b/.github/workflows/Build_OP_Arcadyan_AW1000.yml
@@ -20,7 +20,7 @@ env:
   UPLOAD_BIN_DIR: true
   UPLOAD_FIRMWARE: true
   UPLOAD_RELEASE: true
-  TZ: Asia/Shanghai
+  TZ: Asia/Kuala_Lumpur
   
 jobs:
   build:
@@ -67,7 +67,12 @@ jobs:
         ln -sfn /mnt/openwrt/dl openwrt/dl
         ln -sfn /mnt/openwrt/staging_dir openwrt/staging_dir
         ln -sfn /mnt/openwrt/build_dir openwrt/build_dir
-        
+
+    - name: Copy LEDE Path
+      working-directory: ./openwrt
+      run: |
+       cp target/linux/qualcommax/patches-6.6/0400-mtd-rawnand-add-support-for-TH58NYG3S0HBAI4.patch target/linux/qualcommax/patches-6.1/0400-mtd-rawnand-add-support-for-TH58NYG3S0HBAI4.patch
+    
     - name: Update & Install feeds
       working-directory: ./openwrt
       run: |
@@ -78,10 +83,10 @@ jobs:
         ./scripts/feeds install -a -p nas
         ./scripts/feeds install -a -p nas_luci
 
-    - name: Configuration Customization - Build_Arcadyan_AW1000
+    - name: Configuration Customization 
       run: |
         if [[ ! -f "${CONFIG_FILE}" ]]; then
-          echo "❌ 错误：配置文件 ${CONFIG_FILE} 不存在"
+          echo "❌ Error: Configuration file ${CONFIG_FILE} does not exist"
           ls -l config/ || true
           exit 1
         fi
@@ -94,7 +99,7 @@ jobs:
       id: package
       run: |
         cd openwrt/
-        make download -j$(nproc) || { echo "❌ 下载失败"; exit 1; }
+        make download -j$(nproc) || { echo "❌ Download failed"; exit 1; }
         find dl -size -1024c -delete  
 
     - name: Compile the OpenWrt
@@ -133,12 +138,12 @@ jobs:
       run: |
         echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
         cat <<EOF > release.txt
-        🚀 OpenWrt 固件编译结果
+        🚀 OpenWrt Firmware Build Result
         ----------------------
-        设备: Arcadyan_AW1000
-        时间: $(date +"%Y-%m-%d %H:%M")
-        源码: $REPO_URL
-        分支: $REPO_BRANCH
+        Device: Arcadyan_AW1000
+        Time: $(date +"%Y-%m-%d %H:%M")
+        Source: $REPO_URL
+        Branch: $REPO_BRANCH
         EOF
 
     - name: Upload firmware to release
